### ISSUE TITLE
Invalid imports in the sample code cause project not to build

### ISSUE THREAD

**Issue by seantcanavan** [simenandre/nestjs-envalid#5]
**Describe the bug**
In the sample code the value of `Static` is neither declared or imported.

Also, the default `config.ts` file has no exported member `ENVALID`.

Finally, one of the imports is pulling in the entire `envalid` folder from `node-modules` which is generating additional build errors.

**To Reproduce**
1. Start with a working nestjs project
2. add `"nestjs-envalid": "1.2.0",` to package.json
3. `npm install`
4. navigate to `project/src` and `touch env-config.ts`
5. paste in the sample code from https://github.com/cobraz/nestjs-envalid#quickstart

**Expected behavior**
Typescript project builds successfully

**Screenshots**
![nestjs_envalid_issue](https://user-images.githubusercontent.com/6250751/127354337-9d1d1674-8e28-4151-8f81-d0cf2779db62.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser: FireFox
 - Version: 90

**Comment by simenandre** [comment]
Hello @seantcanavan 👋

Thank for opening this issue! I've seemed to have jumped the fence a bit there, seem to have forgot to export a few things and add a step to the quickstart.

First of all, `envalid` is a peerDependency. We'll have to add that to the steps. I might be mistaken, but that should take care of your build issues? The `ENVALID` export should come from `nestjs-envalid`. I'll look at all this stuff very soon! If you want to open a pull request on this, it would be much appreciated! 👍

Thanks again!

**Comment by seantcanavan** [comment]
Sorry I'm very new to TS/Angular/NestJS so I don't think I'm qualified to open a bug report

**Comment by simenandre** [comment]
This should be fixed now :)
